export const MATCH_STATES = {
  MATCH_FOUND: "MATCH_FOUND",
  COUNTDOWN: "COUNTDOWN",
  ROUND_ACTIVE: "ROUND_ACTIVE",
  ROUND_RESULT: "ROUND_RESULT",
  SUDDEN_DEATH: "SUDDEN_DEATH",
  MATCH_FINISHED: "MATCH_FINISHED",
  FORFEIT: "FORFEIT",
  CANCELLED: "CANCELLED",
};
